var reporting_data = {"lemoncheesecake_version": "1.3.1", "report_version": 1.1, "start_time": "2020-05-16T16:06:08.386Z", "end_time": "2020-05-16T16:06:09.186Z", "generation_time": "2020-05-16T16:06:09.195Z", "nb_threads": 1, "title": "Test Report", "info": [["Command line", "lcc run --tag tutorials, samples, equinix"]], "suites": [{"start_time": "2020-05-16T16:06:08.389Z", "end_time": "2020-05-16T16:06:09.186Z", "tests": [{"start_time": "2020-05-16T16:06:08.390Z", "end_time": "2020-05-16T16:06:09.185Z", "steps": [{"description": "test3", "start_time": "2020-05-16T16:06:08.390Z", "end_time": "2020-05-16T16:06:09.185Z", "entries": [{"type": "check", "description": "Expect http code to be equal to 200", "is_successful": false, "details": "Got 406", "time": "2020-05-16T16:06:09.176Z"}, {"type": "log", "level": "error", "message": "Caught unexpected exception while running test: Traceback (most recent call last):\n  File \"c:\\users\\atpc8\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\lemoncheesecake\\runner.py\", line 188, in run\n    self.test.callback(**test_func_params)\n  File \"C:\\Users\\atpc8\\sdlc\\lemontest\\suites\\firstsuite.py\", line 24, in test3\n    r.json.read()\nAttributeError: 'function' object has no attribute 'read'\n", "time": "2020-05-16T16:06:09.185Z"}]}], "status": "failed", "status_details": null, "name": "test3", "description": "test3", "tags": ["equinix"], "properties": {}, "links": []}], "suites": [], "name": "firstsuite", "description": "my_suite", "tags": ["samples", "tutorials"], "properties": {}, "links": []}]}